[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
itertools = "0.10"
serde_plain = "1"

[dependencies.serde]
version = "1"
features = ["derive"]
